### ISSUE TITLE
http requests are unreliable on startup

### ISSUE THREAD

**Issue by p060477** [majestrate/XD#110] opened 2023-11-15 17:51 UTC
## info

git revision / version: [git revision or version here]

OS: [os here] win 10 home 64

Architecture: [architecture here] 64

## problem  i open an issue here as for suggestion of r4sas 
this is the link https://github.com/PurpleI2P/i2pdbrowser/issues/57#issuecomment-1811160215

webui do not accept torrent urls as stated...this is a BUG Issue

is not working at all, with the torrent's urls i specify, ...:
see the screenshoots just done:

![Immagine](https://github.com/PurpleI2P/i2pdbrowser/assets/12773559/b75347c9-173c-4a31-84e0-e174ff70f34a)

![Immagine2](https://github.com/PurpleI2P/i2pdbrowser/assets/12773559/396d6989-d92e-43b4-bcbd-ebebb7938647)

when i push the green botton on the right : "add"   in the webui
nothing happens:
`[NFO] 2023-11-14 20:56:00.7118568 +0100 CET m=+27.598771501     fetching torrent from http://tracker2.postman.i2p/index.php?action=Download&id=73305
[ERR] 2023-11-14 21:01:13.3621293 +0100 CET m=+340.249010401    failed to fetch torrent: Get "http://tracker2.postman.i2p/index.php?action=Download&id=73305": EOF
[NFO] 2023-11-14 21:01:56.5968622 +0100 CET m=+383.483739001    fetching torrent from http://tracker2.postman.i2p/index.php?action=Download&id=73305
[NFO] 2023-11-14 21:02:04.4372118 +0100 CET m=+391.324087801    fetching torrent from http://tracker2.postman.i2p/index.php?action=Download&id=73305
[ERR] 2023-11-14 21:07:02.6608121 +0100 CET m=+689.547658201    failed to fetch torrent: Get "http://tracker2.postman.i2p/index.php?action=Download&id=73305": EOF
[ERR] 2023-11-14 21:07:10.4985081 +0100 CET m=+697.385353501    failed to fetch torrent: Get "http://tracker2.postman.i2p/index.php?action=Download&id=73305": EOF
[NFO] 2023-11-14 21:21:30.0142494 +0100 CET m=+1556.901008801   fetching torrent from http://tracker2.postman.i2p/index.php?action=Download&id=73305
[ERR] 2023-11-14 21:26:36.5388222 +0100 CET m=+1863.425551001   failed to fetch torrent: Get "http://tracker2.postman.i2p/index.php?action=Download&id=73305": EOF`

[insert description of problem here]

## backtrace / error messages

Error messages: [yes/no]

[insert any error messages here]

Backtrace: [yes/no]

[insert any backtraces here]

**Comment by majestrate** [comment] 2023-11-16 16:38
this happens because we use XD's own SAM session for http fetches which are different from the one used for fetches via a web browser.
adding a option to use a different way to fetch things via http would probably address this.

**Comment by p060477** [comment] 2023-11-16 17:53
so in concret what we could do to be able to finally past a torrent url in the webui and have it finally working...??

**Comment by majestrate** [comment] 2023-11-16 18:15
it will be able to get the torrent if your browser can load the page.

**Comment by p060477** [comment] 2023-11-16 19:04
the browser....which...??...the I2Pd browser 1.3.3...??
cause the browser in which yr webui works is really NOT that...in that browser yr webui cannot add not only torrent urls...but also magnet urls....yr webui : http://127.0.0.1:1776/  works only in a normal browser NOT I2P...as for example my  firefox 119.0.1
in the I2Pd 1.3.3 browser yr webui http://127.0.0.1:1776/ is not working also with magnet urls...
so this is another new BUG issue...isn't it...??

**Comment by majestrate** [comment] 2023-11-16 19:24
On Thursday, November 16, 2023 2:04:13 PM EST p060477 wrote:
> the browser....which...??...the I2Pd browser 1.3.3...??
> cause the browser in which yr webui works is really NOT that...in that
> browser yr webui cannot add not only torrent urls...but also magnet
> urls....yr webui : http://127.0.0.1:1776/  works only in a normal browser
> NOT I2P...as for example my  firefox 119.0.1 in the I2Pd 1.3.3 browser yr
> webui http://127.0.0.1:1776/ is not working also with magnet urls... so
> this is another new BUG issue...isn't it...??

it takes a while for the underlying SAM session to warm up with i2pd.

-- 
~jeff

**Comment by p060477** [comment] 2023-11-16 19:42
what's the meaning of yr reply...??...the question remains unanswered...yr webui state to be able to manage magnet and torrent's urtls...BUT when you try to add a torrent's urls NOTHING happens...so this is still a BUG not solved...??...pls reply clearly...thxs in adv. cheers

**Comment by majestrate** [comment] 2023-11-17 16:37
https://minimaxir.com/2023/11/open-source-dead-github/

**Comment by p060477** [comment] 2023-11-17 17:22
...so **you STATE** that your XD project **is DEAD**...??!!...

**Comment by majestrate** [comment] 2023-11-17 18:03
On Friday, November 17, 2023 12:22:24 PM EST p060477 wrote:
> ...so **you STATE** that your XD project **is DEAD**...??!!...

i can tell you did not read that article.
I'm going to re-create this issue to reduce the clutter in this bug tracker.
Please chill out for a bit.

-- 
~jeff

**Comment by majestrate** [comment] 2023-11-17 18:07
duplicate of #111

**Closed by majestrate** 2023-11-17 18:07 UTC
Labels: enhancement, help wanted
